//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmony022.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Harmony022ModelEntities : DbContext
    {
        public Harmony022ModelEntities()
            : base("name=Harmony022ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblKuca> tblKuca { get; set; }
        public virtual DbSet<tblSlike> tblSlike { get; set; }
        public virtual DbSet<tblStan> tblStan { get; set; }
        public virtual DbSet<tblSlajderGlavni> tblSlajderGlavni { get; set; }
        public virtual DbSet<prikaziPretragaHarmony> prikaziPretragaHarmony { get; set; }
        public virtual DbSet<tblVikendica> tblVikendica { get; set; }
        public virtual DbSet<tblPoslovniProstor> tblPoslovniProstor { get; set; }
        public virtual DbSet<tblZemljiste> tblZemljiste { get; set; }
        public virtual DbSet<tblGradjevinskoZemljiste> tblGradjevinskoZemljiste { get; set; }
    }
}
