//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmony022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prikaziPretragaHarmony
    {
        public string Lokacija { get; set; }
        public string Mesto { get; set; }
        public string Slika { get; set; }
        public int Kvadratura { get; set; }
        public string Drzava { get; set; }
        public int Cena { get; set; }
        public bool Slajder { get; set; }
        public string Vrsta_Nekretnine { get; set; }
        public string Sifra { get; set; }
        public int Stan_Id { get; set; }
        public int Kuca_Id { get; set; }
    }
}
