//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmony022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSlike
    {
        public int slikeId { get; set; }
        public string nekretnina { get; set; }
        public string sifra { get; set; }
        public string referenca { get; set; }
    }
}
